### ISSUE TITLE
Source code of coprocessor

### ISSUE THREAD

**Issue by saeugetier** [Seeed-Studio/MotorBridgeCapeforBBG_BBB#2]
The GPIOs could be used to get feedback from encoders. The source code from the coprocessor is not available. Please make the source code available. So I can implement the encoder and a PID controller by myself. With the source code I don't have to start from beginning.

**Comment by mvduin** [comment]
https://github.com/Seeed-Studio/MotorBridgeCapeFirmwareSourceCode
