### ISSUE TITLE
RE: The MotorBridgeCape for BBG

### ISSUE THREAD

**Issue by silver2row** [Seeed-Studio/MotorBridgeCapeforBBG_BBB#3]
Lee,

There has been some updated work on the SeeedStudio.com site on the forums section. I will try out what the fellow figured out. I will get back to you.

Seth

**Comment by silver2row** [comment]
Hello Again,

Oh and I had to use WinSCP to change the file name to the .zip file that was located on http://www.seeedstudio.com/forum/viewtopic.php?f=38&t=6881&p=25028#p25028. 

It reads as follows.

Hi,

Please try the following steps:

1, Connect cape to your BBG/BBB, download http://www.seeedstudio.com/wiki/images/ ... e_v1.0.zip to your BBG/BBB
2, unzip the file
3, Goto the directory Motor Bridge Cape V1.0 (cd Motor Bridge Cape V1.0)
4, upload firmware (make flash_firmware)

I tried these steps but I was unable to accomplish the task. WinSCP helped me change the .zip file after it was unzipped. I got this as the unzip file, "Motor Bridge Cape v1.0". I needed the .zip file to be unzipped as Motor_Bridge_Cape_v1.0 instead. Since I changed the file name with WinSCP, I was able to get into the files.

Seth
silver2row

P.S. If you need any other info, please contact me.

**Comment by silver2row** [comment]
Okay...I made it to the adding of the Serial port 2 and then I added a line to the Serial port 2. dev/tty02 is already listed in the flasher file.

What should I do from here?

Seth

**Comment by silver2row** [comment]
Hello,

ADC from Adafruit has a bug. I2C has a complication too. Please see the attachments.

Seth
![adafruit and adc](https://cloud.githubusercontent.com/assets/9708195/14929325/9018f4c2-0e22-11e6-896a-a4823b107bfe.JPG)

![adafruit and i2c](https://cloud.githubusercontent.com/assets/9708195/14929341/9dd714c2-0e22-11e6-93ec-2b0403a061d0.JPG)

**Comment by silver2row** [comment]
Okay...

I tried to get the I2C working and I downloaded the Adafruit_BBIO and the rest of the python tools like pip, smbus, and setuptools.

I still am having trouble with this product, i.e. the MotorBridgeCapeforBBG_BBB.

Please see:

Traceback (most recent call last):
  File "DC.py", line 1, in <module>
    import MotorBridge
  File "/root/MotorBridgeCapeforBBG_BBB/BBG_MotorBridgeCape/MotorBridge.py", line 37, in <module>
    MotorBridge = Adafruit_I2C(0x4b)
  File "build/bdist.linux-armv7l/egg/Adafruit_I2C.py", line 17, in __init__
IOError: [Errno 2] No such file or directory


This is what printed out now. I updated my version of Debian to work with the hopes that it would work. I am out of ideas. Do you have any guidance to supply?

Seth

**Comment by silver2row** [comment]
I am still trying. If you come across an ideas, please let me know.

Seth

**Comment by silver2row** [comment]
Hello Lee,

I cannot figure out how that person, Chris, figured out how to configure the device properly. My MotorBridgeCape is still not working. Do you know how to make this add-on board for the BBG work?

Seth

P.S. Please reply with any relative info. you can give.

**Comment by Lee-Kevin** [comment]
Hello Seth, 
Did you update the firmware, if you did't, please follow  [http://www.seeedstudio.com/wiki/Motor_Bridge_Cape_v1.0#Upgrade_the_Firmware](url) to update, if you still have other questions, please come to our forum

**Comment by silver2row** [comment]
Okay...thank you for your support.
