### ISSUE TITLE
Adafruit_I2C has been replaced by Adafruit_GPIO.I2C

### ISSUE THREAD

**Issue by mvduin** [Seeed-Studio/MotorBridgeCapeforBBG_BBB#6]
[Adafruit_I2C](https://github.com/adafruit/adafruit-beaglebone-io-python/blob/master/Adafruit_I2C.py) has been deprecated and is no longer functional. The official replacement is [Adafruit_GPIO.I2C](https://github.com/adafruit/Adafruit_Python_GPIO/blob/master/Adafruit_GPIO/I2C.py).

To fix this issue, replace
```
from Adafruit_I2C import Adafruit_I2C
...
MotorBridge = Adafruit_I2C(0x4b)
```
by
```
import Adafruit_GPIO.I2C as I2C
...
MotorBridge = I2C.Device(0x4b, 2)
```

**Comment by silver2row** [comment]
Hello Sir,

You rule. I do not know how you figured this out and I care but anyway...thank you.

Seth

P.S. I am going to test it now. I will be right back.

**Comment by silver2row** [comment]
Hello...

That does not work for me. I tried it. I get errors w/ this software (MotorBridge.py):

    import Adafruit_GPIO.I2C as I2C
    import Adafruit_GPIO as GPIO
    import time
    Reset = "P9_23"
    MotorBridge = I2C.Device(0x4b, 2)
    GPIO.setup(Reset, GPIO.OUT)

    ReadMode  = 0
    WriteMode = 1
    DeAddr    = 0X4B
    ConfigValid =  0x3a6fb67c
    DelayTime = 0.005

Error Code:

      File "mbcUse.py", line 1, in <module>
        import MotorBridge
      File "/home/debian/MotorBridgeCapeforBBG_BBB/BBG_MotorBridgeCape/MotorBridge.py", line 38, in 
    <module>
        GPIO.setup(Reset, GPIO.OUT)
    AttributeError: 'module' object has no attribute 'setup'

Seth

P.S. It may be an issue w/ setting up "words" versus numerical values, e.g. like in my mbcUse.py software which can be found at https://github.com/silver2row/MotorBridgeCapeforBBG_BBB/blob/silver2row-patches/BBG_MotorBridgeCape/mbcUse.py.

**Comment by silver2row** [comment]
Hello Sir,

See here:

This is my error when I change the line:

    import Adafruit_GPIO as GPIO

to:

    import Adafruit_BBIO.GPIO as GPIO

error codes:

      File "mbcUse.py", line 13, in <module>
        motor.DCMotorInit(1, 1000)
      File "/home/debian/MotorBridgeCapeforBBG_BBB/BBG_MotorBridgeCape/MotorBridge.py", line 279, 
    in DCMotorInit
        WriteOneWord(CONFIG_TB_PWM_FREQ,Frequency)
      File "/home/debian/MotorBridgeCapeforBBG_BBB/BBG_MotorBridgeCape/MotorBridge.py", line 221, 
    in WriteOneWord
        MotorBridge.writeList(WriteMode,data)
      File "build/bdist.linux-armv7l/egg/Adafruit_GPIO/I2C.py", line 128, in writeList
      File "/usr/local/lib/python2.7/dist-packages/Adafruit_PureIO-0.2.1-
    py2.7.egg/Adafruit_PureIO/smbus.py", line 274, in write_i2c_block_data
        self._device.write(data)
    IOError: [Errno 121] Remote I/O error

We are making headway but there is something missing.

My guess would be that the MotorBridge.py library has an error in it. The error is words versus numbers like these numbers from my mbcUse.py file:

    import MotorBridge
    import time

    MotorName        = 1
    MotorName        = 2
    ClockWise        = 1
    CounterClockWise = 2
    PwmDuty          = 90
    Frequency        = 1000

    if __name__=="__main__":
        motor = MotorBridge.MotorBridgeCape()
        motor.DCMotorInit(1, 1000)
        motor.DCMotorInit(2, 1000)
        for i in range(1, 51):
            motor.DCMotorMove(1, 1, 90)
            motor.DCMotorMove(2, 1, 90)
            print "I got your biscuit, now!"

instead of words/values like these:

    import MotorBridge
    import time

    MotorName1        = 1
    MotorName2       = 2
    ClockWise        = 1
    CounterClockWise = 2
    PwmDuty          = 90
    Frequency        = 1000

    if __name__=="__main__":
        motor = MotorBridge.MotorBridgeCape()
        motor.DCMotorInit(MotorName1, Frequency)
        motor.DCMotorInit(MotorName2, Frequency)
        for i in range(1, 51):
            motor.DCMotorMove(MotorName1, ClockWise, PwmDuty)
            motor.DCMotorMove(MotorName2, ClockWise, PwmDuty)
            print "I got your biscuit, now!"

I have typed up the mbcUse.py software before w/ the MotorBridge.py library while using the Adafruit_BBIO library w/ numerical values and word values. Both have been attempted and used w/out a hitch.

Seth

P.S. If you are getting different error codes or if this software runs w/out a hitch, please let me know. I still am having an issue w/ running this older software w/ these two libraries.

**Comment by mvduin** [comment]
Ehm, the errors in your first comment were caused by the random other changes you made to the source code other than the two changes I mentioned (I never said anything about changing the `import Adafruit_BBIO.GPIO as GPIO` line).  Then it seems you noticed that and fixed it back to what it was, and subsequently got an i2c error ("Remote I/O error", i.e. the i2c peripheral did not respond). The stuff you say after that seems unintelligible to me (you're blaming the use of variables or something? what?).

The i2c error could perhaps be due to having screwed up some system config (such as the pinmux of P9.19-20, which is correct by default but can be manually altered) or is perhaps caused by hardware issues (e.g. poor connection, or damage to the motor controller). In any case, the python code itself was probably working correctly at that point.

**Comment by silver2row** [comment]
I changed things back and forth, I rebooted, and then I ran the software again. I got the same i/o error.

Seth

**Comment by silver2row** [comment]
Okay...Hello,

Seth here. I updated my entire PC. I had to reset b/c the damn thing was going goofy on me. Anyway, long story short, I got all my issues for my PC resolved.

I tried the above software change for the MotorBridge.py library.

It failed. 

I get the error:

    Traceback (most recent call last):
      File "mbcUse.py", line 1, in <module>
        import MotorBridge
      File "/home/debian/MotorBridgeCapeforBBG_BBB/BBG_MotorBridgeCape/MotorBridge.py", line 33, in 
    <module>
        import Adafruit_GPIO.I2C as I2C
    ImportError: No module named Adafruit_GPIO.I2C

Seth

P.S. This is odd. I updated to Adafruit_BBIO 1.0.10 to get the bug fixes but I have come across another issue/error this time.

**Comment by silver2row** [comment]
Hello Once More,

I have left the software here respectively:

    import Adafruit_GPIO.I2C as I2C
    import Adafruit_BBIO.GPIO as GPIO
    import time
    Reset = "P9_23"
    MotorBridge = I2C.Device(0x4b, 2)
    GPIO.setup(Reset, GPIO.OUT)

Seth

P.S. If you notice something different, please let me know.

**Comment by silver2row** [comment]
Okay and Hello,

I updated and got Adafruit_GPIO from: https://github.com/adafruit/Adafruit_Python_GPIO.

I changed the software to suit the needs of this #6 issue. Here is my new issue:

Just for reference (in case there are other people w/ this issue):

    Traceback (most recent call last):
      File "mbcUse.py", line 13, in <module>
        motor.DCMotorInit(1, 1000)
      File "/home/debian/MotorBridgeCapeforBBG_BBB/BBG_MotorBridgeCape/MotorBridge.py", line 279, 
    in DCMotorInit
        WriteOneWord(CONFIG_TB_PWM_FREQ,Frequency)
      File "/home/debian/MotorBridgeCapeforBBG_BBB/BBG_MotorBridgeCape/MotorBridge.py", line 221, 
    in 
        WriteOneWord
        MotorBridge.writeList(WriteMode,data)
      File "build/bdist.linux-armv7l/egg/Adafruit_GPIO/I2C.py", line 129, in writeList
      File "/usr/local/lib/python2.7/dist-packages/Adafruit_PureIO-0.2.1-
    py2.7.egg/Adafruit_PureIO/smbus.py", line 274, in write_i2c_block_data
        self._device.write(data)
    IOError: [Errno 121] Remote I/O error

Seth

P.S. mvduin, you do not need to reply to this post any longer. You told me you like irc better. I will keep the irc channel for future use.

**Comment by silver2row** [comment]
Hello Again,

Seth here. I wanted to apologize for using your workaround instead of making my own. I tried to give you credit w/out naming you on the software change by referring to #6 on this Seeed-Studio/MotorBridgeCapeforBBG_BBB section.

I will change it if necessary. If you want me to change #6 to mvduin or your any other name, please let me know. I was not trying to plagarize your work w/out giving your credit to you. 

Seth

P.S. So...instead of #6, I can change it to suit your needs since you came up w/ that workaround. Sorry.

**Comment by mvduin** [comment]
What on _earth_ are you rambling about? The only real issue you've mentioned so far is that remote i/o error, which is off-topic for this thread. I'll maybe try to help you with it on irc when I'm less annoyed. I have not the slightest clue what you are even talking about in your last comment and I'm going to ignore it. Please do not add any further comments to this github issue.

**Comment by raffaeleGrandi** [comment]
Hi guys,
there are some links where I can find code examples in order to understand how to properly use Adafruit_GPIO.I2C module? Tnx in advance.

**Comment by silver2row** [comment]
Hello,

Adafruit_GPIO.I2C is now in a read-only state on github.com.

Seth

**Comment by baorepo** [comment]
@silver2row  good job
